name: Linter
on:
  push:
  pull_request: 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Golangci-lint
      uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 #v2.5.2
      with:
        version: v1.42
        args: --verbose
